Repository PaiGramTeam/PaiGram, pull requests merged in 2022-09, with the labels that each got.

#93 ✨ 使用 alembic 管理数据库版本
  README.md
  alembic.ini
  alembic/README.md
  alembic/env.py
  alembic/script.py.mako
  alembic/versions/9e9a36470cd5_init.py
  core/admin/models.py
  core/cookies/models.py
  core/quiz/models.py
  core/sign/models.py
  core/user/models.py
  poetry.lock
  pyproject.toml
Labels: enhancement ✨

#96 ✨ 添加角色卡片插件
  README.md
  modules/playercards/fight_prop.py
  modules/playercards/helpers.py
  modules/playercards/metadata/FightPropRule.json
  plugins/genshin/player_cards.py
  resources/genshin/player_card/artifacts.html
  resources/genshin/player_card/constellations.html
  resources/genshin/player_card/img/bg-anemo.jpg
  resources/genshin/player_card/img/bg-cryo.jpg
  resources/genshin/player_card/img/bg-dendro.jpg
  resources/genshin/player_card/img/bg-electro.jpg
  resources/genshin/player_card/img/bg-geo.jpg
  resources/genshin/player_card/img/bg-hydro.jpg
  resources/genshin/player_card/img/bg-pyro.jpg
  resources/genshin/player_card/img/star.png
  resources/genshin/player_card/img/talent-anemo.png
  resources/genshin/player_card/img/talent-cryo.png
  resources/genshin/player_card/img/talent-dendro.png
  resources/genshin/player_card/img/talent-electro.png
  resources/genshin/player_card/img/talent-geo.png
  resources/genshin/player_card/img/talent-hydro.png
  resources/genshin/player_card/img/talent-pyro.png
  resources/genshin/player_card/player_card.css
  resources/genshin/player_card/player_card.html
  resources/genshin/player_card/score.html
  resources/genshin/player_card/skills.html
  resources/genshin/player_card/stats.html
  resources/genshin/player_card/weapon.html
  resources/js/tailwindcss-3.1.8.js
Labels: enhancement ✨, approved ✅

#97 ♻️ 重写 `restricts` 修饰器
  plugins/genshin/gacha/gacha.py
  plugins/genshin/player_cards.py
  plugins/genshin/quiz.py
  utils/decorators/restricts.py
Labels: enhancement ✨, approved ✅

#100 ⬆ Create Dependency Policy
  .github/dependabot.yml
Labels: dependencies ⬆

#106 ✨ 米游社支持直接通过手机号绑定
  .gitignore
  modules/apihelper/hyperion.py
  plugins/genshin/cookies.py
Labels: enhancement ✨

#102 ✨ 今日素材表
  core/assets/__init__.py
  core/assets/service.py
  core/bot.py
  metadata/honey.py
  metadata/shortname.py
  modules/wiki/material.py
  plugins/genshin/daily/__init__.py
  plugins/genshin/daily/material.py
  resources/genshin/daily_material/bg/area/0.png
  resources/genshin/daily_material/bg/area/1.png
  resources/genshin/daily_material/bg/area/2.png
  resources/genshin/daily_material/bg/area/3.png
  resources/genshin/daily_material/bg/rarity/full/1.png
  resources/genshin/daily_material/bg/rarity/full/2.png
  resources/genshin/daily_material/bg/rarity/full/3.png
  resources/genshin/daily_material/bg/rarity/full/4.png
  resources/genshin/daily_material/bg/rarity/full/5.png
  resources/genshin/daily_material/bg/rarity/half/1.png
  resources/genshin/daily_material/bg/rarity/half/2.png
  resources/genshin/daily_material/bg/rarity/half/3.png
  resources/genshin/daily_material/bg/rarity/half/4.png
  resources/genshin/daily_material/bg/rarity/half/5.png
  resources/genshin/daily_material/bg/rarity/star.webp
  resources/genshin/daily_material/bg/title/01.png
  resources/genshin/daily_material/bg/title/02.png
  resources/genshin/daily_material/character.html
  resources/genshin/daily_material/example.html
  resources/genshin/daily_material/style.css
  resources/genshin/daily_material/weapon.html
  tests/test_wiki.py
  utils/const.py
  utils/helpers.py
  utils/typedefs.py
Labels: enhancement ✨

#111 🐛 修复模板复用不正确导致的错误并改进代码避免触发洪水模式
  .gitignore
  core/admin/services.py
  core/assets/__init__.py
  core/template/services.py
  plugins/genshin/daily/material.py
Labels: bug 🐛

#115 🎨 改进 `daily_material` 模块
  plugins/genshin/daily/material.py
  poetry.lock
  pyproject.toml
  resources/genshin/daily_material/character.html
  resources/genshin/daily_material/example.html
  resources/genshin/daily_material/style.css
  resources/genshin/daily_material/weapon.html
  utils/helpers.py
Labels: enhancement ✨
