Repository PaiGramTeam/PaiGram, pull requests merged in 2022-11, with the labels that each got.

#244 ✨ Send uid to geetest verification site
  plugins/genshin/sign.py
Labels: approved ✅

#251 🚚 Change resources repo
  core/bot.py
  metadata/scripts/metadatas.py
Labels: pending review 🔬

#255 ✨ Pass verification
  modules/apihelper/helpers.py
  modules/apihelper/hyperion.py
  modules/apihelper/request/hoyorequest.py
  plugins/genshin/verification.py
  plugins/system/start.py
  utils/decorators/error.py
Labels: enhancement ✨, approved ✅

#265 🐛 Fix material cache error
  core/game/cache.py
  core/game/services.py
Labels: bug 🐛, approved ✅

#266 ✨ Add Webapp
  modules/apihelper/hyperion.py
  plugins/genshin/verification.py
  plugins/system/start.py
  plugins/system/webapp.py
Labels: enhancement ✨, approved ✅

#268 🐛 Fix material character weapon miss
  plugins/genshin/daily/material.py
Labels: bug 🐛, approved ✅

#269 ✨ add method `get_link` for AssetsService
  core/base/assets.py
  metadata/genshin.py
Labels: enhancement ✨, approved ✅

#275 ⬆ Update PTB related dependencies and add version check
  core/bot.py
  modules/gacha_log/log.py
  plugins/genshin/gacha/gacha_log.py
  poetry.lock
  pyproject.toml
Labels: enhancement ✨, dependencies ⬆, approved ✅

#276 ✨ Raise `SystemExit` exception after core initialization error to shut down the app
  core/base/aiobrowser.py
  core/base/mysql.py
  core/base/redisdb.py
  core/bot.py
Labels: enhancement ✨, approved ✅

#278 ✨ Added code to generate the device_id from the v2 cookies
  utils/patch/genshin.py
Labels: enhancement ✨, approved ✅

#279 ✨ Added code to get the old account_id
  modules/apihelper/hyperion.py
  plugins/genshin/cookies.py
Labels: bug 🐛, approved ✅

#277 🎨 Update get cookie help message
  plugins/genshin/cookies.py
Labels: documentation 📝, approved ✅
