Repository PaiGramTeam/PaiGram, pull requests merged in 2022-12, with the labels that each got.

#285 🐛 fix cookies
  plugins/genshin/cookies.py
Labels: bug 🐛, approved ✅

#287 ✨ Add inline search
  core/search/__init__.py
  core/search/models.py
  core/search/services.py
  metadata/shortname.py
  plugins/genshin/strategy.py
  plugins/genshin/weapon.py
  plugins/system/inline.py
  plugins/system/search.py
  poetry.lock
  pyproject.toml
Labels: enhancement ✨, approved ✅

#290 🐛 fix `AssetsService`
  core/base/assets.py
  modules/gacha_log/log.py
  plugins/genshin/daily/material.py
Labels: bug 🐛, pending review 🔬

#292 🐛 fix cookie parser
  plugins/genshin/cookies.py
Labels: bug 🐛, approved ✅

#289 ♻ Refactor ApiHelper
  .env.example
  core/game/services.py
  modules/apihelper/__init__.py
  modules/apihelper/client/__init__.py
  modules/apihelper/client/base/__init__.py
  modules/apihelper/client/base/httpxrequest.py
  modules/apihelper/client/base/hyperionrequest.py
  modules/apihelper/client/components/__init__.py
  modules/apihelper/client/components/abyss.py
  modules/apihelper/client/components/gacha.py
  modules/apihelper/client/components/hyperion.py
  modules/apihelper/client/components/signin.py
  modules/apihelper/client/components/verify.py
  modules/apihelper/hyperion.py
  modules/apihelper/logger.py
  modules/apihelper/models/__init__.py
  modules/apihelper/models/genshin/__init__.py
  modules/apihelper/models/genshin/abyss.py
  modules/apihelper/models/genshin/gacha.py
  modules/apihelper/models/genshin/hyperion.py
  modules/apihelper/typedefs.py
  modules/apihelper/utility/__init__.py
  modules/apihelper/utility/helpers.py
  plugins/genshin/abyss_team.py
  plugins/genshin/cookies.py
  plugins/genshin/gacha/gacha.py
  plugins/genshin/gacha/gacha_log.py
  plugins/genshin/sign.py
  plugins/genshin/verification.py
  plugins/other/post.py
  plugins/system/start.py
  plugins/system/webapp.py
  tests/test_abyss_team_data.py
  tests/test_hyperion.py
  tests/test_hyperion_bbs.py
  utils/genshin.py
  utils/patch/genshin.py
Labels: refactor ♻, approved ✅

#305 ✨ Use qrcode to add cookies only CN users
  modules/apihelper/client/components/signin.py
  plugins/genshin/cookies.py
  poetry.lock
  pyproject.toml
Labels: enhancement ✨, pending review 🔬

#304 🍱 Update Roles Short Name
  metadata/shortname.py
Labels: code quality 🎨, approved ✅

#309 🎨 Improve code quality
  core/base/assets.py
  core/bot.py
  metadata/scripts/metadatas.py
  plugins/genshin/avatar_list.py
  plugins/genshin/cookies.py
  plugins/genshin/daily/material.py
  plugins/genshin/verification.py
  plugins/jobs/sign.py
  plugins/system/admin.py
  plugins/system/get_chat.py
  plugins/system/new_member.py
  plugins/system/set_quiz.py
  plugins/system/start.py
  plugins/system/update.py
  utils/decorators/restricts.py
  utils/helpers.py
  utils/log/__init__.py
  utils/log/_handler.py
Labels: code quality 🎨, Do not merge (yet) ⛔️
