Repository PaiGramTeam/PaiGram, pull requests merged in 2022-10, with the labels that each got.

#127 ✨ gacha 缓存 12 小时卡池数据
  modules/apihelper/gacha.py
Labels: enhancement ✨

#131 修复上游 `genshin.py` 更新后导致的错误
  core/bot.py
  plugins/genshin/userstats.py
  utils/patch/__init__.py
Labels: bug 🐛

#132 ✨ 支持深境螺旋推荐配队
  modules/apihelper/abyss_team.py
  plugins/genshin/abyss_team.py
  resources/bot/help/help.html
  resources/genshin/abyss_team/abyss_team.html
  resources/genshin/abyss_team/example.html
  tests/test_abyss_team_data.py
Labels: enhancement ✨

#129 ✨ Enhance AssetsService
  core/assets/__init__.py
  core/assets/service.py
  core/base/assets.py
  metadata/genshin.py
  metadata/honey.py
  metadata/scripts/honey.py
  metadata/scripts/metadatas.py
  metadata/shortname.py
  modules/apihelper/abyss_team.py
  modules/wiki/base.py
  modules/wiki/character.py
  modules/wiki/material.py
  modules/wiki/metadata/ascension.json
  modules/wiki/metadata/elite.json
  modules/wiki/metadata/monster.json
  modules/wiki/other.py
  modules/wiki/weapon.py
  plugins/genshin/abyss.py
  plugins/genshin/abyss_team.py
  plugins/genshin/daily/material.py
  plugins/genshin/refresh_metadata.py
  plugins/genshin/weapon.py
  resources/genshin/abyss/abyss.html
  resources/genshin/abyss/example.html
  resources/genshin/daily_material/example.html
  resources/genshin/daily_material/style.css
  utils/const.py
  utils/helpers.py
  utils/typedefs.py
Labels: enhancement ✨, approved ✅

#134 ✨ 支持管理员获取用户详细信息
  core/cookies/repositories.py
  plugins/system/get_chat.py
Labels: enhancement ✨

#138 🎨 重写 `apihelper` 模块
  core/game/services.py
  modules/apihelper/artifact.py
  modules/apihelper/base.py
  modules/apihelper/error.py
  modules/apihelper/gacha.py
  modules/apihelper/hoyolab.py
  modules/apihelper/hyperion.py
  modules/apihelper/request/hoyorequest.py
  modules/apihelper/request/httpxrequest.py
  modules/apihelper/typedefs.py
  plugins/genshin/cookies.py
  plugins/genshin/gacha/gacha.py
  plugins/other/post.py
  tests/test_game.py
  tests/test_hyperion_bbs.py
  utils/decorators/error.py
Labels: refactor ♻, approved ✅

#142 ✨ 添加更新命令功能
  .gitignore
  plugins/system/update.py
  utils/helpers.py
Labels: enhancement ✨

#140 ✨ 支持抽卡记录导入/导出
  metadata/pool/pool.py
  metadata/pool/pool_200.py
  metadata/pool/pool_301.py
  metadata/pool/pool_302.py
  modules/apihelper/gacha_log.py
  plugins/genshin/gacha/__init__.py
  plugins/genshin/gacha/gacha_log.py
  resources/genshin/gacha_count/example.html
  resources/genshin/gacha_count/gacha_count.css
  resources/genshin/gacha_count/gacha_count.html
  resources/genshin/gacha_log/example.html
  resources/genshin/gacha_log/gacha_log.css
  resources/genshin/gacha_log/gacha_log.html
  resources/genshin/gacha_log/img/提纳里.png
Labels: enhancement ✨

#146 ⚡️ 优化导入抽卡记录命令，无需绑定 Cookie
  modules/apihelper/gacha_log.py
  plugins/genshin/gacha/gacha_log.py
  plugins/system/get_chat.py
  utils/helpers.py
Labels: refactor ♻

#148 ✨ gacha_log 支持删除数据
  metadata/shortname.py
  modules/apihelper/gacha_log.py
  plugins/genshin/gacha/gacha_log.py
  plugins/system/get_chat.py
Labels: enhancement ✨

#150 👷 CI 添加缓存
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/test.yml
  plugins/system/get_chat.py
Labels: enhancement ✨

#152 ⚡️ 为抽卡分析添加缓存
  core/base/assets.py
  metadata/shortname.py
  modules/apihelper/gacha_log.py
  plugins/genshin/player_cards.py
Labels: bug 🐛

#153 ✨ 给签到添加ajax请求或打码平台
  core/config.py
  plugins/genshin/sign.py
  plugins/jobs/sign.py
  plugins/system/sign_all.py
Labels: enhancement ✨

#157 ✨ 支持通过 Stoken 自动刷新抽卡记录
  core/config.py
  metadata/shortname.py
  modules/apihelper/hyperion.py
  plugins/genshin/gacha/gacha_log.py
  plugins/genshin/sign.py
  plugins/jobs/sign.py
  utils/log/_logger.py
Labels: enhancement ✨

#159 🎨 提高代码质量
  core/bot.py
  core/template/services.py
  core/wiki/cache.py
  modules/apihelper/gacha_log.py
  plugins/genshin/cookies.py
  plugins/genshin/daily/material.py
  plugins/genshin/gacha/gacha_log.py
  plugins/genshin/player_cards.py
  plugins/other/post.py
  plugins/system/errorhandler.py
  utils/log/_logger.py
  utils/patch/aiohttp.py
Labels: code quality 🎨, approved ✅

#161 🐛 修复对话中 cancel 命令失效
  core/plugin.py
  plugins/other/post.py
Labels: bug 🐛, approved ✅

#158 ✨ 在绑定 Cookie 时尝试自动获取 stoken
  modules/apihelper/hyperion.py
  plugins/genshin/cookies.py
Labels: enhancement ✨, pending review 🔬

#162 🎨 Update `help.html`
  plugins/genshin/help.py
  resources/bot/help/help.html
Labels: documentation 📝, approved ✅

#165 ✨ Add `SignAgain` Job
  plugins/genshin/sign.py
  plugins/jobs/sign.py
Labels: enhancement ✨, approved ✅

#166 🎨 Update the text of a reply when bot query user does not exist
  plugins/genshin/abyss_team.py
  plugins/genshin/cookies.py
  plugins/genshin/daily_note.py
  plugins/genshin/gacha/gacha_log.py
  plugins/genshin/ledger.py
  plugins/genshin/map/map.py
  plugins/genshin/player_cards.py
  plugins/genshin/sign.py
  plugins/genshin/userstats.py
  plugins/system/start.py
  resources/bot/help/help.html
Labels: documentation 📝, approved ✅

#170 🐛 修复 `abyss`
  plugins/genshin/abyss.py
Labels: bug 🐛, approved ✅

#172 ✨ 支持自动签到统计信息
  plugins/genshin/sign.py
  plugins/jobs/sign.py
  plugins/system/sign_status.py
Labels: enhancement ✨, approved ✅

#164 ✨ 增加用于模板预览和调试的 web server
  .env.example
  core/base/webserver.py
  core/config.py
  core/service.py
  core/template/README.md
  core/template/__init__.py
  core/template/cache.py
  core/template/services.py
  plugins/genshin/abyss.py
  plugins/genshin/abyss_team.py
  plugins/genshin/daily/material.py
  plugins/genshin/daily_note.py
  plugins/genshin/gacha/gacha.py
  plugins/genshin/gacha/gacha_log.py
  plugins/genshin/help.py
  plugins/genshin/ledger.py
  plugins/genshin/player_cards.py
  plugins/genshin/userstats.py
  plugins/genshin/weapon.py
  poetry.lock
  pyproject.toml
  resources/genshin/ledger/ledger.html
  resources/genshin/player_card/player_card.html
Labels: enhancement ✨, pending review 🔬

#175 ✨ 为 `post` 插件添加定时推送功能
  .env.example
  modules/apihelper/hyperion.py
  plugins/other/post.py
  tests/test_hyperion_bbs.py
Labels: enhancement ✨, approved ✅

#176 ✨ 加强后验证功能
  plugins/system/auth.py
Labels: enhancement ✨, approved ✅

#174 ✨ enhance logger
  .env.example
  core/base/webserver.py
  core/config.py
  utils/log/_handler.py
  utils/log/_logger.py
  utils/log/_traceback.py
Labels: enhancement ✨, approved ✅

#178 🍱 更新武器别名
  metadata/shortname.py
Labels: documentation 📝, approved ✅

#179 🐛 修复提前抽取卡池
  modules/apihelper/hyperion.py
  plugins/genshin/gacha/gacha.py
Labels: bug 🐛, pending review 🔬

#183 ♻ 重写抽卡模拟器插件
  metadata/genshin.py
  modules/apihelper/hyperion.py
  modules/gacha/banner.py
  plugins/genshin/gacha/gacha.py
  plugins/genshin/gacha/wish.py
  resources/bot/help/help.html
  resources/genshin/gacha/gacha.css
  resources/genshin/gacha/gacha.html
  resources/genshin/gacha/items/Electric.png
  resources/genshin/gacha/items/Fire.png
  resources/genshin/gacha/items/Grass.png
  resources/genshin/gacha/items/Ice.png
  resources/genshin/gacha/items/Rock.png
  resources/genshin/gacha/items/WEAPON_BOW.png
  resources/genshin/gacha/items/WEAPON_CATALYST.png
  resources/genshin/gacha/items/WEAPON_CLAYMORE.png
  resources/genshin/gacha/items/WEAPON_POLE.png
  resources/genshin/gacha/items/WEAPON_SWORD_ONE_HAND.png
  resources/genshin/gacha/items/Water.png
  resources/genshin/gacha/items/Wind.png
Labels: refactor ♻

#184 🐛 修正`.env.example`的traceback相关设置
  .env.example
Labels: approved ✅

#180 ✨ 角色练度查询
  plugins/genshin/avatar_list.py
  poetry.lock
  resources/genshin/avatar_list/example.html
  resources/genshin/avatar_list/main.html
  resources/genshin/avatar_list/style.css
  resources/img/crown.png
  resources/img/logo.png
Labels: enhancement ✨, approved ✅

#186 🐛 avatar 修复错误
  plugins/genshin/avatar_list.py
  utils/patch/__init__.py
  utils/patch/genshin.py
Labels: bug 🐛, approved ✅

#191 ✨ 添加错误平台
  .env.example
  core/config.py
  modules/error/pb.py
  modules/error/sentry.py
  plugins/system/errorhandler.py
  plugins/system/log.py
  poetry.lock
  pyproject.toml
  utils/log/_handler.py
Labels: enhancement ✨, Do not merge (yet) ⛔️

#196 :sparkles: gacha_log 支持导入从 paimon.moe 和非小酋导出的抽卡记录
  modules/apihelper/gacha_log.py
  plugins/genshin/gacha/gacha_log.py
  poetry.lock
  pyproject.toml
  resources/json/zh.json
Labels: enhancement ✨, approved ✅

#198 🐛 修复未知命令不回复
  core/bot.py
Labels: bug 🐛, pending review 🔬

#197 ♻️ 重构 `gacha_log`
  metadata/scripts/paimon_moe.py
  metadata/shortname.py
  modules/apihelper/error.py
  modules/gacha_log/const.py
  modules/gacha_log/error.py
  modules/gacha_log/helpers.py
  modules/gacha_log/log.py
  modules/gacha_log/models.py
  plugins/genshin/gacha/gacha_log.py
  plugins/system/get_chat.py
  plugins/system/refresh_metadata.py
  resources/json/zh.json
Labels: refactor ♻, approved ✅

#204 🐛 修复 `refresh_metadata`
  metadata/scripts/metadatas.py
Labels: bug 🐛, approved ✅, Improve performance ⚡️

#192 ✨ 增加 html to image 的缓存
  core/template/__init__.py
  core/template/cache.py
  core/template/error.py
  core/template/models.py
  core/template/services.py
  plugins/genshin/abyss.py
  plugins/genshin/abyss_team.py
  plugins/genshin/avatar_list.py
  plugins/genshin/daily/material.py
  plugins/genshin/daily_note.py
  plugins/genshin/gacha/gacha_log.py
  plugins/genshin/help.py
  plugins/genshin/ledger.py
  plugins/genshin/player_cards.py
  plugins/genshin/userstats.py
  plugins/genshin/weapon.py
Labels: enhancement ✨, breaking💥, approved ✅, Improve performance ⚡️

#205 ⚡ 给 `genshin.py` 添加 Redis cache
  utils/helpers.py
Labels: approved ✅, Improve performance ⚡️

#211 🎨 优化报错提醒
  plugins/genshin/abyss.py
  plugins/genshin/abyss_team.py
  plugins/genshin/artifact_rate.py
  plugins/genshin/avatar_list.py
  plugins/genshin/daily/material.py
  plugins/genshin/daily_note.py
  plugins/genshin/gacha/gacha.py
  plugins/genshin/gacha/gacha_log.py
  plugins/genshin/ledger.py
  plugins/genshin/player_cards.py
  plugins/genshin/sign.py
  plugins/genshin/userstats.py
  plugins/system/start.py
Labels: code quality 🎨, pending review 🔬

#216 🎨 改进 `logger`
  .env.example
  core/config.py
  utils/log/__init__.py
  utils/log/_config.py
  utils/log/_file.py
  utils/log/_handler.py
  utils/log/_logger.py
  utils/log/_traceback.py
  utils/typedefs.py
Labels: code quality 🎨, pending review 🔬

#227 ➖ remove numpy
  plugins/genshin/quiz.py
  plugins/system/auth.py
  poetry.lock
  pyproject.toml
  utils/random.py
Labels: approved ✅

#225 🔧 Add docker integration
  .dockerignore
  Dockerfile
Labels: enhancement ✨, pending review 🔬

#230 🎨 Improve `config`
  alembic/env.py
  core/base/webserver.py
  core/config.py
  core/template/services.py
  modules/error/pb.py
  modules/error/sentry.py
  plugins/system/errorhandler.py
  utils/const.py
  utils/log/__init__.py
  utils/models/base.py
Labels: code quality 🎨, pending review 🔬

#232 🎨 Use `random` module instead of `secrets` module
  modules/gacha/system.py
  plugins/genshin/userstats.py
  plugins/jobs/sign.py
  plugins/system/sign_all.py
Labels: approved ✅

#234 ✨ Add gacha_count only_five_star support
  modules/gacha_log/log.py
  plugins/genshin/gacha/gacha_log.py
Labels: enhancement ✨, pending review 🔬

#235 🎨 Adjust effective artifact stats for some characters
  modules/playercards/metadata/FightPropRule.json
Labels: Improve 🎨

#190 ✨Character birthday query
  metadata/genshin.py
  plugins/genshin/birthday.py
  resources/bot/help/help.html
Labels: enhancement ✨

#236 ✨ Support manual pass challenge
  core/bot.py
  core/config.py
  plugins/genshin/sign.py
  plugins/system/start.py
Labels: enhancement ✨, pending review 🔬

#237 🔒️ Impore sign in group security
  plugins/genshin/sign.py
  plugins/system/start.py
Labels: enhancement ✨, approved ✅

#238 ♻ Refactor sign system
  plugins/genshin/sign.py
  plugins/jobs/sign.py
  plugins/system/sign_all.py
  plugins/system/start.py
Labels: refactor ♻, approved ✅
