Repository PaiGramTeam/PaiGram, pull requests merged in 2022-08, with the labels that each got.

#76 ✨丘丘语字典
  plugins/genshin/hilichurls.py
  resources/json/hilichurls_dictionary.json
Labels: enhancement

#79 🔧 使用 dotenv 重构 config
  .env.example
  .gitignore
  config.py
  config/config.json.example
  core/admin/services.py
  core/template/services.py
  jobs/sign.py
  logger.py
  main.py
  plugins/genshin/help.py
  plugins/genshin/post.py
  plugins/system/errorhandler.py
  requirements.txt
  utils/helpers.py
  utils/storage.py
Labels: refactor ♻

#78 ♻️ 重写 wiki
  core/wiki/cache.py
  core/wiki/services.py
  metadata/shortname.py
  models/wiki/base.py
  models/wiki/character.py
  models/wiki/characters.py
  models/wiki/helpers.py
  models/wiki/material.py
  models/wiki/metadata/weapon_level.json
  models/wiki/other.py
  models/wiki/weapon.py
  models/wiki/weapons.py
  plugins/genshin/weapon.py
  resources/genshin/weapon/weapon.html
  test/model/wiki/test_wiki.py
Labels: refactor ♻

#86 ♻️ 重写 wiki
  core/wiki/cache.py
  core/wiki/services.py
  metadata/shortname.py
  models/wiki/base.py
  models/wiki/character.py
  models/wiki/characters.py
  models/wiki/helpers.py
  models/wiki/material.py
  models/wiki/metadata/weapon_level.json
  models/wiki/other.py
  models/wiki/weapon.py
  models/wiki/weapons.py
  plugins/genshin/weapon.py
  resources/genshin/weapon/weapon.html
  test/model/wiki/test_wiki.py
Labels: refactor ♻

#87 🐛 修复 windows 下路径问题
  models/base.py
  utils/manager.py
Labels: bug 🐛

#77 ✨修复 `quiz` 模块问题并添加验证群验证插件
  .env.example
  config.py
  core/quiz/__init__.py
  core/quiz/cache.py
  core/quiz/models.py
  core/quiz/repositories.py
  core/quiz/services.py
  plugins/base.py
  plugins/genshin/quiz.py
  plugins/system/auth.py
  utils/plugins/register.py
Labels: enhancement ✨

#82 ✨ 添加请求速率限制器
  main.py
Labels: enhancement ✨

#83 📝 更新文档
  README.md
  plugins/README.md
Labels: documentation 📝

#84 🎨 提高代码质量
  jobs/public_cookies.py
  plugins/base.py
  plugins/genshin/uid.py
  plugins/genshin/weapon.py
  plugins/system/inline.py
Labels: code quality 🎨

#88 ✨ 新增 角色培养素材查询 功能
  core/game/__init__.py
  core/game/cache.py
  core/game/services.py
  plugins/genshin/material.py
  plugins/system/inline.py
Labels: enhancement ✨

#89 🐛 修复 redis 中无数据时的错误
  core/wiki/cache.py
  core/wiki/services.py
  plugins/system/auth.py
Labels: bug 🐛

#92 🐛 修复角色素材部分角色缺失
  core/game/services.py
  plugins/genshin/material.py
Labels: bug 🐛
