Repository PaiGramTeam/PaiGram, pull requests merged in 2023-09, with the labels that each got.

#641 :art: Add Cookies status update
  plugins/account/cookies.py
  plugins/account/players.py
  plugins/jobs/refresh_cookies.py
  plugins/tools/genshin.py
Labels: approved ✅, Improve 🎨

#645 :sparkles: Support get gacha log url
  plugins/genshin/wish_log.py
Labels: enhancement ✨, pending review 🔬

#647 :sparkles: Support hoyolab redeem code
  plugins/app/start.py
  plugins/genshin/redeem.py
Labels: enhancement ✨, pending review 🔬

#650 :bug: Fix photo invalid dimensions
  modules/apihelper/client/components/hyperion.py
  modules/apihelper/models/genshin/hyperion.py
Labels: bug :bug:, pending review 🔬

#654 :bug: Fix post cut text and photo error
  plugins/admin/post.py
Labels: bug :bug:, pending review 🔬
