Repository PaiGramTeam/PaiGram, pull requests merged in 2023-08, with the labels that each got.

#618 :sparkles: qlogin support get full token
  modules/apihelper/client/components/authclient.py
  modules/apihelper/models/genshin/cookies.py
  plugins/account/cookies.py
Labels: enhancement ✨, pending review 🔬

#620 Change the calculation for up-average pulls
  modules/gacha_log/log.py
Labels: bug :bug:, approved ✅

#626 :bug: Fix incorrect matching with commands containing `@`
  plugins/genshin/abyss.py
Labels: bug :bug:
