Repository PaiGramTeam/PaiGram, pull requests merged in 2023-02, with the labels that each got.

#385 ✨ Support Docker Compose
  .gitignore
  Dockerfile
  README.md
  docker-compose.gen.yml
Labels: documentation 📝, enhancement ✨, approved ✅

#389 Reg time
  modules/apihelper/client/components/signin.py
  plugins/genshin/reg_time.py
  utils/genshin.py
  utils/patch/genshin.py
Labels: enhancement ✨, approved ✅

#390 ✨ Support Get Birthday Card
  plugins/genshin/birthday.py
  resources/bot/help/help.html
Labels: enhancement ✨, approved ✅

#411 ⬆️ Bump all dependencies
  poetry.lock
  requirements.txt
Labels: dependencies ⬆, pending review 🔬

#418 ✨ Support calendar
  core/base/assets.py
  metadata/scripts/metadatas.py
  modules/apihelper/client/components/calendar.py
  modules/apihelper/models/genshin/calendar.py
  plugins/genshin/birthday.py
  plugins/genshin/calendar.py
  resources/bot/help/help.html
  resources/genshin/calendar/calendar.css
  resources/genshin/calendar/calendar.html
  resources/genshin/calendar/calendar.less
  resources/genshin/calendar/common.css
  resources/genshin/calendar/common.less
  resources/genshin/calendar/example.html
  resources/genshin/calendar/img/abyss-icon.png
  resources/genshin/calendar/img/abyss.jpg
  resources/genshin/calendar/img/card-bg.png
  resources/genshin/calendar/img/fetter.png
Labels: enhancement ✨, approved ✅

#423 🎨 Add Download File Size Setting
  .env.example
  core/config.py
  plugins/genshin/gacha/gacha_log.py
Labels: enhancement ✨, pending review 🔬

#424 🐛 Avoid gacha log import block main thread
  modules/gacha_log/log.py
Labels: bug 🐛, pending review 🔬

#425 ✨ Post support gif
  modules/apihelper/client/components/hyperion.py
  modules/apihelper/models/genshin/hyperion.py
  plugins/other/post.py
  tests/test_hyperion_bbs.py
Labels: enhancement ✨, approved ✅

#428 ♻️ Refactor Map
  modules/apihelper/client/components/map.py
  modules/apihelper/models/genshin/map.py
  plugins/genshin/map.py
  plugins/genshin/map/__init__.py
  plugins/genshin/map/map.py
  plugins/genshin/map/model.py
  poetry.lock
  pyproject.toml
  requirements.txt
  resources/img/map.png
Labels: refactor ♻, pending review 🔬

#430 🎨 Update Networking backend tweaks
  .env.example
  core/bot.py
  core/config.py
Labels: pending review 🔬

#447 ☁️ Use remote birthday
  .github/workflows/test.yml
  modules/apihelper/client/components/calendar.py
  modules/apihelper/client/components/remote.py
  plugins/genshin/birthday.py
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement ✨, pending review 🔬
