Repository PaiGramTeam/PaiGram, pull requests merged in 2023-11, with the labels that each got.

#681 ✨ Support Akasha System
  modules/apihelper/client/components/akasha.py
  modules/apihelper/models/genshin/akasha.py
  plugins/genshin/akasha.py
  resources/genshin/akasha/char_rank.jinja2
  resources/genshin/akasha/char_rank_example.html
  resources/genshin/akasha/style.css
Labels: enhancement ✨, approved ✅

#687 ✨ Use stoken v2 instead of v1
  plugins/account/cookies.py
  plugins/account/players.py
Labels: enhancement ✨, pending review 🔬

#686 :recycle: refactor `/daily_material`
  plugins/genshin/daily/material.py
Labels: breaking💥, pending reply, Improve 🎨

#699 🔨Fix help_raw command
  .gitignore
  plugins/genshin/help_raw.py
Labels: approved ✅

#700 :sparkles: Add Set Command Plugin and Fix Some Bug
  plugins/admin/set_command.py
  plugins/genshin/daily_note_tasks.py
  plugins/genshin/player_cards.py
  resources/bot/help/help.jinja2
Labels: pending review 🔬, Do not merge (yet) ⛔️

#705 🔨Fix handle CookiesCachePoolExhausted gracefully
  plugins/account/account.py
Labels: Do not merge (yet) ⛔️

#706 ✨ Filter the same type of error
  plugins/system/errorhandler.py
Labels: enhancement ✨, approved ✅
