Repository PaiGramTeam/PaiGram, pull requests merged in 2023-04, with the labels that each got.

#506 ⬆️ Upgrade dependencies
  .github/workflows/poetry.yml
  requirements.txt
Labels: dependencies ⬆, Update Lockfile and Requirements

#520 🐛 Fix post cannot get text
  plugins/admin/post.py
Labels: bug 🐛, approved ✅

#530 🚚 Isolated recognize method
  plugins/tools/recognize.py
  plugins/tools/sign.py
  poetry.lock
  requirements.txt
Labels: dependencies ⬆, approved ✅, Improve 🎨

#537 ✨ Support name card
  plugins/genshin/pay_log.py
  plugins/genshin/wish_log.py
  plugins/tools/player_info.py
  resources/genshin/pay_log/pay_log.jinja2
  resources/genshin/wish_count/example.html
  resources/genshin/wish_count/wish_count.css
  resources/genshin/wish_count/wish_count.jinja2
  resources/genshin/wish_log/example.html
  resources/genshin/wish_log/img/提纳里.png
  resources/genshin/wish_log/wish_log.css
  resources/genshin/wish_log/wish_log.jinja2
Labels: enhancement ✨, approved ✅
