Repository PaiGramTeam/PaiGram, pull requests merged in 2023-01, with the labels that each got.

#327 Update README.md
  README.md
Labels: documentation 📝

#331 🐛 fix avatar list get name_card
  metadata/scripts/metadatas.py
  plugins/genshin/avatar_list.py
Labels: bug 🐛, pending review 🔬

#332 Adjust sort rules in `avatar_list.py`
  plugins/genshin/avatar_list.py
Labels: approved ✅, Improve 🎨

#334 Add optional password for Redis
  .env.example
  core/base/redisdb.py
  core/config.py
Labels: enhancement ✨, approved ✅

#336 Update `help.html`
  plugins/genshin/help.py
  resources/bot/help/help.html
Labels: documentation 📝, approved ✅

#339 Doc: fix command notice in `resources\genshin\avatar_list\main.html`
  resources/genshin/avatar_list/main.html
Labels: bug 🐛, documentation 📝

#341 ✨ Support pay log
  modules/pay_log/error.py
  modules/pay_log/log.py
  modules/pay_log/models.py
  plugins/genshin/pay_log.py
  plugins/system/get_chat.py
  poetry.lock
  resources/genshin/pay_log/echarts.min.js
  resources/genshin/pay_log/example.html
  resources/genshin/pay_log/pay_log.css
  resources/genshin/pay_log/pay_log.html
Labels: enhancement ✨, approved ✅

#342 🎨 move all `user_mismatch` notice to the same place
  .env.example
  core/config.py
  plugins/genshin/player_cards.py
  plugins/genshin/sign.py
  plugins/system/auth.py
Labels: approved ✅, Improve 🎨

#343 🐛 fix abyss HTML template
  resources/genshin/abyss/overview.html
Labels: bug 🐛, enhancement ✨, pending review 🔬

#345 ♻️ Refactor services for v4
  core/dependence/mysql.py
  core/services/admin/__init__.py
  core/services/admin/cache.py
  core/services/admin/models.py
  core/services/admin/repositories.py
  core/services/admin/services.py
  core/services/cookies/__init__.py
  core/services/cookies/cache.py
  core/services/cookies/error.py
  core/services/cookies/models.py
  core/services/cookies/repositories.py
  core/services/cookies/services.py
  core/services/game/services.py
  core/services/players/__init__.py
  core/services/players/models.py
  core/services/players/repositories.py
  core/services/players/services.py
  core/services/quiz/cache.py
  core/services/quiz/models.py
  core/services/quiz/repositories.py
  core/services/quiz/services.py
  core/services/search/models.py
  core/services/search/services.py
  core/services/sign/models.py
  core/services/sign/repositories.py
  core/services/user/__init__.py
  core/services/user/models.py
  core/services/user/repositories.py
  core/services/user/services.py
  core/services/users/__init__.py
  core/services/users/cache.py
  core/services/users/error.py
  core/services/users/models.py
  core/services/users/repositories.py
  core/services/users/services.py
  core/sqlmodel/session.py
  utils/helpers.py
Labels: code quality 🎨, breaking💥, pending review 🔬, v4 🌟

#362 :pencil: update `Shortname.py` & :apple: add `.gitignore` for macOS
  .gitignore
  metadata/shortname.py
Labels: documentation 📝, translation 🌐, Improve 🎨

#364 :pencil: add pay_log description to `help.html`
  resources/bot/help/help.html
Labels: documentation 📝

#363 ✨ Support File Cache Player Cards
  modules/pay_log/log.py
  modules/playercards/file.py
  plugins/genshin/player_cards.py
  plugins/system/get_chat.py
Labels: enhancement ✨, approved ✅

#371 fix: CookiesNotFoundError when setcookie
  core/cookies/services.py
  plugins/genshin/cookies.py
Labels: bug 🐛, approved ✅

#347 🐛 Fix some bugs in v4 core
  core/baseplugin.py
  core/bot.py
  core/builtins/contexts.py
  core/builtins/dispatcher.py
  core/builtins/executor.py
  core/helpers.py
  core/manager.py
  core/plugin/__init__.py
  core/plugin/_funcs.py
  core/plugin/_handler.py
  core/plugin/_job.py
  core/plugin/_plugin.py
  core/services/cookies/repositories.py
  core/services/cookies/services.py
  core/services/game/cache.py
  core/services/game/services.py
  core/services/players/models.py
  core/services/players/repositories.py
  core/services/players/services.py
  core/services/users/models.py
  core/services/users/services.py
  modules/apihelper/client/components/signin.py
  modules/override/__init__.py
  modules/override/telegram.py
  plugins/helpers/__init__.py
  plugins/helpers/genshin.py
  run.py
  utils/bot.py
  utils/const/__init__.py
  utils/const/_path.py
  utils/decorators/admins.py
  utils/decorators/error.py
  utils/decorators/restricts.py
  utils/helpers.py
  utils/typedefs/__init__.py
  utils/typedefs/_generics.py
Labels: enhancement ✨, breaking💥, approved ✅
