Repository PaiGramTeam/PaiGram, pull requests merged in 2023-10, with the labels that each got.

#655 :bug: Fix setcookies IntegrityError
  plugins/account/account.py
  plugins/account/cookies.py
Labels: enhancement ✨

#670 :sparkles: Add Transformative Damage Support
  plugins/genshin/player_cards.py
  resources/genshin/player_card/damage.jinja2
Labels: enhancement ✨, pending review 🔬

#674 :recycle: Refactor `daily_material` sort_item
  plugins/genshin/daily/material.py
Labels: code quality 🎨, approved ✅, pending merge, Improve 🎨
